In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data_sources/wikipedia/ISO3166_country_code/iso3166_country_code.csv')
df.head()

,name,official_state_name,sovereignty,ISO3166-1_alpha-2,ISO3166-1_alpha-3,ISO3166-1_numeric,subdivision_code,iternet_cc_tld
0,Afghanistan,The Islamic Republic of Afghanistan,UN member state,AF,AFG,4,ISO 3166-2:AF,.af
1,Åland Islands,Åland,Finland,AX,ALA,248,ISO 3166-2:AX,.ax
2,Albania,The Republic of Albania,UN member state,AL,ALB,8,ISO 3166-2:AL,.al
3,Algeria,The People's Democratic Republic of Algeria,UN member state,DZ,DZA,12,ISO 3166-2:DZ,.dz
4,American Samoa,The Territory of American Samoa,United States,AS,ASM,16,ISO 3166-2:AS,.as

In [23]:
pd.concat([pd.read_csv('../data_sources/wikipedia/ISO3166_country_code/iso3166_country_code.csv', 
                       usecols=['name', 'ISO3166-1_alpha-3']).rename(columns={'name': 'country_name', 'ISO3166-1_alpha-3': 'country_code'}), 
          pd.read_csv('../data_sources/wikipedia/ISO3166_country_code/iso3166_country_code.csv', 
                      usecols=['official_state_name', 'ISO3166-1_alpha-3']).rename(
              columns={'official_state_name': 'country_name', 'ISO3166-1_alpha-3': 'country_code'}), 
          pd.read_csv('../data_sources/worldbank_population_data/wb_raw.csv', usecols=['country', 'country_code']).rename(
    columns={'country': 'country_name'})]).drop_duplicates().sort_values(by=['country_code']).reset_index(drop=True)[['country_code', 'country_name']]

    country_code                         country_name
0            ABW                                Aruba
1            AFG                          Afghanistan
2            AFG  The Islamic Republic of Afghanistan
3            AGO               The Republic of Angola
4            AGO                               Angola
..           ...                                  ...
548          ZAF                         South Africa
549          ZMB               The Republic of Zambia
550          ZMB                               Zambia
551          ZWE             The Republic of Zimbabwe
552          ZWE                             Zimbabwe

[553 rows x 2 columns]

     country_name country_code
0           Aruba          ABW
1     Afghanistan          AFG
2          Angola          AGO
3         Albania          ALB
4         Andorra          AND
..            ...          ...
259        Kosovo          XKX
260   Yemen, Rep.          YEM
261  South Africa          ZAF
262        Zambia          ZMB
263      Zimbabwe          ZWE

[264 rows x 2 columns]